[package]
name = "rusty8080"
version = "0.1.0"
authors = ["Andrew Hopkins <andrewjohnhopkins@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
log = "0.4"
log4rs = "0.8.1"
piston_window = "0.81.0"
